name: Rerendering README file

on:
  push:
    branches:
      - main
      
jobs:
  render_my_file:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      
    - name: Install Quarto CLI
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: LATEST
        
    - name: Install R packzges
      run: |
        Rscript -e "install.packages('renv', repos = 'https://packagemanager.posit.com/cran/latest')"
        Rscript -e "renv::restore(repos = 'https://packagemanager.posit.com/cran/latest')"
        
    - name: Rerender Quarto file
      run: |
        quarto render README.qmd
        
    - name: Commit readme.md file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README.md from readme.qmd"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}