name: Rerendering README file

on:
  schedule:
    - cron: '10 1 * * *'
  push:
    branches:
      - main
      
jobs:
  render_my_file:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      
    - name: install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.1' # The R version to download (if necessary) and use.
    # Use "renv" to retrieve R version recorded in renv.lock file.
      
    - name: Install Quarto CLI
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: LATEST
        
    - name: Install R packages
      run: |
        Rscript -e "install.packages('renv', repos = 'https://packagemanager.posit.co/cran/latest')"
        Rscript -e "renv::restore(repos = 'https://packagemanager.posit.co/cran/latest')"
        
    - name: Rerender Quarto file
      run: |
        quarto render README.qmd
        
    - name: Commit readme.md file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README.md from readme.qmd"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
